package bumblebee.util

object StringObj {
    const val WIDTH = "width"
    const val HEIGHT = "height"
    const val BIT_COUNT = "bitCount"
    const val COMPONENT = "component"
    const val SIZE = "size"
    const val START_OFFSET = "startOffset"
    const val DATA = "data"
    const val TYPE = "type"
    const val CRC = "crc"
    const val NAME = "name"
    const val IDENTIFIER = "identifier"
    const val TEXT = "text"
    const val ENDIAN = "endian"
    const val TRANSITION_METHOD = "transitionMethod"
    const val COEFFICIENT = "coefficient"
    const val PRECISION = "precision"
    const val RESTART_INTERVAL = "restartInterval"
    const val UNITS = "units"
    const val VERSION = "version"
    const val X_DENSITY = "xDensity"
    const val X_THUMBNAIL = "xThumbnail"
    const val Y_THUMBNAIL = "yThumbnail"
    const val Y_DENSITY = "yDensity"
}